import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
const migration=await readFile(new URL("../supabase/migrations/20261007152657_owner_calendar_events.sql",import.meta.url),"utf8");
const db=new PGlite();
const owner="00000000-0000-0000-0000-000000000001",other="00000000-0000-0000-0000-000000000002",dog="10000000-0000-0000-0000-000000000001",otherDog="10000000-0000-0000-0000-000000000002";
await db.exec(`create schema auth; create role anon; create role authenticated; create role service_role;
  create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
  grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated;
  create table public.wt_dogs(id uuid primary key,owner_id uuid references auth.users(id));
  grant select on public.wt_dogs to authenticated;
  insert into auth.users values ('${owner}'),('${other}'); insert into public.wt_dogs values ('${dog}','${owner}'),('${otherDog}','${other}');`);
await db.exec(migration);
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${owner}',false);`);
await db.query("insert into wt_calendar_events(owner_id,dog_id,category,title,start_date,end_date) values($1,$2,'travel','旅行','2026-10-07','2026-10-09')",[owner,dog]);
await assert.rejects(db.query("insert into wt_calendar_events(owner_id,dog_id,category,title,start_date,end_date) values($1,$2,'travel','他人の犬','2026-10-07','2026-10-09')",[owner,otherDog]),/row-level security/);
await assert.rejects(db.query("insert into wt_calendar_events(owner_id,dog_id,category,title,start_date,end_date) values($1,$2,'travel','所有者偽装','2026-10-07','2026-10-09')",[other,dog]),/row-level security/);
await assert.rejects(db.query("update wt_calendar_events set dog_id=$1",[otherDog]),/row-level security/);
for(const sql of ["update wt_calendar_events set end_date='2026-10-06'","update wt_calendar_events set title=' '","update wt_calendar_events set category='invalid'","update wt_calendar_events set end_date='2028-10-07'"])await assert.rejects(db.exec(sql),/check constraint/);
await db.exec(`select set_config('request.jwt.claim.sub','${other}',false);`);
assert.equal((await db.query("select * from wt_calendar_events")).rows.length,0);
assert.equal((await db.query("delete from wt_calendar_events returning id")).rows.length,0);
await db.exec(`reset role; set role anon;`);
await assert.rejects(db.query("select * from wt_calendar_events"),/permission denied/);
await db.exec(`reset role; delete from wt_dogs where id='${dog}';`);
assert.equal((await db.query("select * from wt_calendar_events")).rows.length,0);
assert.equal((await db.query("select * from wt_dogs")).rows.length,1);
await db.close(); console.log("Calendar migration: constraints, owner isolation, foreign dog protection, anonymous denial and cascade deletion passed.");
