-- Phase 1A: observation data foundation.
-- Run after 029_dog_profile_avatar.sql.
--
-- This migration intentionally does not modify or backfill wt_daily_records.

create table public.wt_dog_observation_themes (
  id uuid primary key default gen_random_uuid(),
  dog_id uuid not null references public.wt_dogs(id) on delete cascade,
  theme_key text not null check (
    theme_key in (
      'barking',
      'walk',
      'alone',
      'toilet',
      'dog_reaction',
      'person_reaction',
      'biting',
      'meal',
      'sleep_rest',
      'grooming'
    )
  ),
  sort_order smallint not null check (sort_order between 1 and 3),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (dog_id, theme_key),
  unique (dog_id, sort_order)
);

comment on table public.wt_dog_observation_themes is
  'Up to three canonical observation themes selected for each dog.';
comment on column public.wt_dog_observation_themes.sort_order is
  'Positions 1-3 also enforce the per-dog maximum without a race-prone count trigger.';

create table public.wt_observation_entries (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  dog_id uuid not null references public.wt_dogs(id) on delete cascade,
  entry_kind text not null check (entry_kind in ('daily_check', 'event')),
  theme_key text,
  occurred_at timestamptz not null,
  timezone text not null default 'Asia/Tokyo' check (char_length(timezone) between 1 and 100),
  local_date date not null,
  note text check (note is null or char_length(note) <= 5000),
  schema_version integer not null default 1 check (schema_version > 0),
  source text not null default 'owner' check (source in ('owner', 'coach', 'import')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint wt_observation_entries_theme_check check (
    (entry_kind = 'daily_check' and theme_key is null)
    or
    (
      entry_kind = 'event'
      and theme_key in (
        'barking',
        'walk',
        'alone',
        'toilet',
        'dog_reaction',
        'person_reaction',
        'biting',
        'meal',
        'sleep_rest',
        'grooming'
      )
    )
  ),
  constraint wt_observation_entries_deleted_at_check check (
    deleted_at is null or deleted_at >= created_at
  )
);

comment on table public.wt_observation_entries is
  'Common immutable identity and timing data for daily checks and event logs.';
comment on column public.wt_observation_entries.local_date is
  'Derived by the database from occurred_at in the stored IANA timezone.';
comment on column public.wt_observation_entries.theme_key is
  'Null for holistic daily checks and required for event logs.';
comment on column public.wt_observation_entries.id is
  'May be supplied by an offline client; otherwise generated by PostgreSQL.';

create table public.wt_daily_checks (
  entry_id uuid primary key references public.wt_observation_entries(id) on delete cascade,
  appetite_score smallint check (appetite_score between 1 and 5),
  sleep_rest_score smallint check (sleep_rest_score between 1 and 5),
  activity_score smallint check (activity_score between 1 and 5),
  exploration_score smallint check (exploration_score between 1 and 5),
  calmness_score smallint check (calmness_score between 1 and 5),
  toilet_score smallint check (toilet_score between 1 and 5),
  constraint wt_daily_checks_has_score_check check (
    num_nonnulls(
      appetite_score,
      sleep_rest_score,
      activity_score,
      exploration_score,
      calmness_score,
      toilet_score
    ) > 0
  )
);

comment on table public.wt_daily_checks is
  'One-to-one daily state scores; null means not answered and is never treated as zero.';
comment on column public.wt_daily_checks.appetite_score is
  '1=very concerning, 2=slightly concerning, 3=usual, 4=good, 5=very good.';

create table public.wt_observation_events (
  entry_id uuid primary key references public.wt_observation_entries(id) on delete cascade,
  event_result text not null check (event_result in ('success', 'neutral', 'concern')),
  state_before text check (
    state_before is null
    or state_before in ('calm', 'excited', 'tired', 'hungry', 'uneasy', 'unknown')
  ),
  environment_key text check (
    environment_key is null
    or environment_key in ('home', 'street', 'park', 'cafe', 'shop', 'daycare', 'vehicle', 'other')
  ),
  situation_keys text[],
  behavior_keys text[],
  target_type text check (
    target_type is null
    or target_type in ('dog', 'person', 'sound', 'object', 'owner', 'none', 'other')
  ),
  distance_band text check (
    distance_band is null
    or distance_band in ('under_1m', '1_3m', '3_5m', '5_10m', 'over_10m', 'unknown')
  ),
  intensity smallint check (intensity is null or intensity between 1 and 10),
  duration_seconds integer check (duration_seconds is null or duration_seconds between 0 and 604800),
  owner_response_keys text[],
  outcome text check (
    outcome is null
    or outcome in ('no_reaction', 'settled_quickly', 'partly_settled', 'unchanged', 'escalated')
  ),
  recovery_seconds integer check (recovery_seconds is null or recovery_seconds between 0 and 604800),
  success boolean,
  theme_data jsonb not null default '{}'::jsonb check (jsonb_typeof(theme_data) = 'object'),
  constraint wt_observation_events_situation_keys_check check (
    situation_keys is null
    or (
      cardinality(situation_keys) between 0 and 20
      and array_position(situation_keys, null) is null
      and array_position(situation_keys, '') is null
    )
  ),
  constraint wt_observation_events_behavior_keys_check check (
    behavior_keys is null
    or (
      cardinality(behavior_keys) between 0 and 20
      and array_position(behavior_keys, null) is null
      and array_position(behavior_keys, '') is null
    )
  ),
  constraint wt_observation_events_owner_response_keys_check check (
    owner_response_keys is null
    or (
      cardinality(owner_response_keys) between 0 and 20
      and array_position(owner_response_keys, null) is null
      and array_position(owner_response_keys, '') is null
    )
  )
);

comment on table public.wt_observation_events is
  'One-to-one structured event details used for explainable trend analysis.';
comment on column public.wt_observation_events.event_result is
  'Exposure-level result, including successful and neutral events as well as concerns.';
comment on column public.wt_observation_events.success is
  'Optional explicit result for a theme-specific goal; event_result remains the common exposure classification.';
comment on column public.wt_observation_events.theme_data is
  'Theme-specific, versioned attributes only. Common analysis dimensions use typed columns.';

-- Derive local_date from the timestamp and validated timezone on every write.
-- The owner/dog assertion prevents inconsistent ownership even for privileged writes.
create or replace function public.wt_prepare_observation_entry()
returns trigger
language plpgsql
set search_path = public, pg_catalog
as $$
begin
  if not exists (
    select 1 from pg_catalog.pg_timezone_names where name = new.timezone
  ) then
    raise exception 'unsupported observation timezone: %', new.timezone
      using errcode = '22023';
  end if;

  if not exists (
    select 1 from public.wt_dogs dog
    where dog.id = new.dog_id and dog.owner_id = new.owner_id
  ) then
    raise exception 'observation owner does not own the selected dog'
      using errcode = '23514';
  end if;

  if tg_op = 'UPDATE' then
    if new.owner_id <> old.owner_id
       or new.dog_id <> old.dog_id
       or new.entry_kind <> old.entry_kind
       or new.source <> old.source then
      raise exception 'observation owner, dog, kind, and source are immutable'
        using errcode = '23514';
    end if;
    new.created_at := old.created_at;
  end if;

  new.local_date := (new.occurred_at at time zone new.timezone)::date;
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function public.wt_prepare_observation_entry() from public, anon, authenticated;

create trigger wt_prepare_observation_entry_before_write
  before insert or update on public.wt_observation_entries
  for each row execute function public.wt_prepare_observation_entry();

create or replace function public.wt_touch_observation_theme()
returns trigger
language plpgsql
set search_path = public, pg_catalog
as $$
begin
  new.created_at := old.created_at;
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function public.wt_touch_observation_theme() from public, anon, authenticated;

create trigger wt_touch_observation_theme_before_update
  before update on public.wt_dog_observation_themes
  for each row execute function public.wt_touch_observation_theme();

-- Enforce the one-to-one subtype and parent entry_kind relationship.
create or replace function public.wt_validate_observation_subtype()
returns trigger
language plpgsql
set search_path = public, pg_catalog
as $$
declare
  expected_kind text := tg_argv[0];
begin
  if not exists (
    select 1 from public.wt_observation_entries entry
    where entry.id = new.entry_id and entry.entry_kind = expected_kind
  ) then
    raise exception 'observation subtype requires entry_kind %', expected_kind
      using errcode = '23514';
  end if;
  return new;
end;
$$;

revoke all on function public.wt_validate_observation_subtype() from public, anon, authenticated;

create trigger wt_validate_daily_check_before_write
  before insert or update on public.wt_daily_checks
  for each row execute function public.wt_validate_observation_subtype('daily_check');

create trigger wt_validate_observation_event_before_write
  before insert or update on public.wt_observation_events
  for each row execute function public.wt_validate_observation_subtype('event');

-- One active daily check per dog and local calendar date. Soft-deleted entries do
-- not occupy the date, so a replacement can be created while retaining history.
create unique index wt_observation_entries_daily_check_day_uidx
  on public.wt_observation_entries(dog_id, local_date)
  where entry_kind = 'daily_check' and deleted_at is null;

create index wt_observation_entries_dog_occurred_idx
  on public.wt_observation_entries(dog_id, occurred_at desc)
  where deleted_at is null;

create index wt_observation_entries_owner_occurred_idx
  on public.wt_observation_entries(owner_id, occurred_at desc)
  where deleted_at is null;

create index wt_observation_entries_dog_theme_occurred_idx
  on public.wt_observation_entries(dog_id, theme_key, occurred_at desc)
  where deleted_at is null and theme_key is not null;

create index wt_observation_entries_dog_kind_occurred_idx
  on public.wt_observation_entries(dog_id, entry_kind, occurred_at desc)
  where deleted_at is null;

-- GIN indexes are limited to the three multi-select dimensions expected in the
-- first Insight queries. theme_data stays unindexed until real query patterns exist.
create index wt_observation_events_situation_keys_gin_idx
  on public.wt_observation_events using gin(situation_keys);

create index wt_observation_events_behavior_keys_gin_idx
  on public.wt_observation_events using gin(behavior_keys);

create index wt_observation_events_owner_response_keys_gin_idx
  on public.wt_observation_events using gin(owner_response_keys);

alter table public.wt_dog_observation_themes enable row level security;
alter table public.wt_observation_entries enable row level security;
alter table public.wt_daily_checks enable row level security;
alter table public.wt_observation_events enable row level security;

-- Selected observation themes: owners manage their dog's rows, assigned coaches
-- can read, and administrators retain the existing full-management convention.
create policy "owners select own dog observation themes"
  on public.wt_dog_observation_themes for select to authenticated
  using (
    exists (
      select 1 from public.wt_dogs dog
      where dog.id = wt_dog_observation_themes.dog_id
        and dog.owner_id = auth.uid()
    )
  );

create policy "owners insert own dog observation themes"
  on public.wt_dog_observation_themes for insert to authenticated
  with check (
    exists (
      select 1 from public.wt_dogs dog
      where dog.id = wt_dog_observation_themes.dog_id
        and dog.owner_id = auth.uid()
    )
  );

create policy "owners update own dog observation themes"
  on public.wt_dog_observation_themes for update to authenticated
  using (
    exists (
      select 1 from public.wt_dogs dog
      where dog.id = wt_dog_observation_themes.dog_id
        and dog.owner_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.wt_dogs dog
      where dog.id = wt_dog_observation_themes.dog_id
        and dog.owner_id = auth.uid()
    )
  );

create policy "owners delete own dog observation themes"
  on public.wt_dog_observation_themes for delete to authenticated
  using (
    exists (
      select 1 from public.wt_dogs dog
      where dog.id = wt_dog_observation_themes.dog_id
        and dog.owner_id = auth.uid()
    )
  );

create policy "assigned coaches read dog observation themes"
  on public.wt_dog_observation_themes for select to authenticated
  using (
    public.wt_is_coach()
    and exists (
      select 1 from public.wt_coach_assignments assignment
      where assignment.coach_id = auth.uid()
        and assignment.dog_id = wt_dog_observation_themes.dog_id
    )
  );

create policy "admins manage dog observation themes"
  on public.wt_dog_observation_themes for all to authenticated
  using (public.wt_is_admin())
  with check (public.wt_is_admin());

-- Common entries: owners have CRUD for their own dog, assigned coaches are
-- read-only, and administrators follow the existing management model.
create policy "owners select own observation entries"
  on public.wt_observation_entries for select to authenticated
  using (
    owner_id = auth.uid()
    and exists (
      select 1 from public.wt_dogs dog
      where dog.id = wt_observation_entries.dog_id
        and dog.owner_id = auth.uid()
    )
  );

create policy "owners insert own observation entries"
  on public.wt_observation_entries for insert to authenticated
  with check (
    owner_id = auth.uid()
    and source = 'owner'
    and exists (
      select 1 from public.wt_dogs dog
      where dog.id = wt_observation_entries.dog_id
        and dog.owner_id = auth.uid()
    )
  );

create policy "owners update own observation entries"
  on public.wt_observation_entries for update to authenticated
  using (
    owner_id = auth.uid()
    and exists (
      select 1 from public.wt_dogs dog
      where dog.id = wt_observation_entries.dog_id
        and dog.owner_id = auth.uid()
    )
  )
  with check (
    owner_id = auth.uid()
    and exists (
      select 1 from public.wt_dogs dog
      where dog.id = wt_observation_entries.dog_id
        and dog.owner_id = auth.uid()
    )
  );

create policy "owners delete own observation entries"
  on public.wt_observation_entries for delete to authenticated
  using (
    owner_id = auth.uid()
    and exists (
      select 1 from public.wt_dogs dog
      where dog.id = wt_observation_entries.dog_id
        and dog.owner_id = auth.uid()
    )
  );

create policy "assigned coaches read observation entries"
  on public.wt_observation_entries for select to authenticated
  using (
    public.wt_is_coach()
    and exists (
      select 1 from public.wt_coach_assignments assignment
      where assignment.coach_id = auth.uid()
        and assignment.dog_id = wt_observation_entries.dog_id
    )
  );

create policy "admins manage observation entries"
  on public.wt_observation_entries for all to authenticated
  using (public.wt_is_admin())
  with check (public.wt_is_admin());

-- Subtype rows inherit access from their parent entry. Coaches receive SELECT
-- only; there are deliberately no coach INSERT/UPDATE/DELETE policies.
create policy "owners select own daily checks"
  on public.wt_daily_checks for select to authenticated
  using (
    exists (
      select 1 from public.wt_observation_entries entry
      where entry.id = wt_daily_checks.entry_id
        and entry.owner_id = auth.uid()
    )
  );

create policy "owners insert own daily checks"
  on public.wt_daily_checks for insert to authenticated
  with check (
    exists (
      select 1 from public.wt_observation_entries entry
      where entry.id = wt_daily_checks.entry_id
        and entry.owner_id = auth.uid()
    )
  );

create policy "owners update own daily checks"
  on public.wt_daily_checks for update to authenticated
  using (
    exists (
      select 1 from public.wt_observation_entries entry
      where entry.id = wt_daily_checks.entry_id
        and entry.owner_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.wt_observation_entries entry
      where entry.id = wt_daily_checks.entry_id
        and entry.owner_id = auth.uid()
    )
  );

create policy "owners delete own daily checks"
  on public.wt_daily_checks for delete to authenticated
  using (
    exists (
      select 1 from public.wt_observation_entries entry
      where entry.id = wt_daily_checks.entry_id
        and entry.owner_id = auth.uid()
    )
  );

create policy "assigned coaches read daily checks"
  on public.wt_daily_checks for select to authenticated
  using (
    public.wt_is_coach()
    and exists (
      select 1
      from public.wt_observation_entries entry
      join public.wt_coach_assignments assignment on assignment.dog_id = entry.dog_id
      where entry.id = wt_daily_checks.entry_id
        and assignment.coach_id = auth.uid()
    )
  );

create policy "admins manage daily checks"
  on public.wt_daily_checks for all to authenticated
  using (public.wt_is_admin())
  with check (public.wt_is_admin());

create policy "owners select own observation events"
  on public.wt_observation_events for select to authenticated
  using (
    exists (
      select 1 from public.wt_observation_entries entry
      where entry.id = wt_observation_events.entry_id
        and entry.owner_id = auth.uid()
    )
  );

create policy "owners insert own observation events"
  on public.wt_observation_events for insert to authenticated
  with check (
    exists (
      select 1 from public.wt_observation_entries entry
      where entry.id = wt_observation_events.entry_id
        and entry.owner_id = auth.uid()
    )
  );

create policy "owners update own observation events"
  on public.wt_observation_events for update to authenticated
  using (
    exists (
      select 1 from public.wt_observation_entries entry
      where entry.id = wt_observation_events.entry_id
        and entry.owner_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.wt_observation_entries entry
      where entry.id = wt_observation_events.entry_id
        and entry.owner_id = auth.uid()
    )
  );

create policy "owners delete own observation events"
  on public.wt_observation_events for delete to authenticated
  using (
    exists (
      select 1 from public.wt_observation_entries entry
      where entry.id = wt_observation_events.entry_id
        and entry.owner_id = auth.uid()
    )
  );

create policy "assigned coaches read observation events"
  on public.wt_observation_events for select to authenticated
  using (
    public.wt_is_coach()
    and exists (
      select 1
      from public.wt_observation_entries entry
      join public.wt_coach_assignments assignment on assignment.dog_id = entry.dog_id
      where entry.id = wt_observation_events.entry_id
        and assignment.coach_id = auth.uid()
    )
  );

create policy "admins manage observation events"
  on public.wt_observation_events for all to authenticated
  using (public.wt_is_admin())
  with check (public.wt_is_admin());

grant select, insert, update, delete on public.wt_dog_observation_themes to authenticated;
grant select, insert, update, delete on public.wt_observation_entries to authenticated;
grant select, insert, update, delete on public.wt_daily_checks to authenticated;
grant select, insert, update, delete on public.wt_observation_events to authenticated;
